In [2]:
import pandas as pd

weatherDF = pd.read_csv("weather_data.csv", encoding="cp949")
weatherDF = weatherDF[["지점명", "일시", "기온(°C)"]] # 필요한 컬럼만 다시 대입
weatherDF

        지점 지점명                일시  기온(°C)
0      108  서울  2020-01-01 00:00    -6.5
1      108  서울  2020-01-01 01:00    -5.9
2      108  서울  2020-01-01 02:00    -5.7
3      108  서울  2020-01-01 03:00    -5.6
4      108  서울  2020-01-01 04:00    -5.4
...    ...  ..               ...     ...
17557  159  부산  2020-12-31 19:00     0.6
17558  159  부산  2020-12-31 20:00     0.1
17559  159  부산  2020-12-31 21:00    -0.2
17560  159  부산  2020-12-31 22:00    -0.7
17561  159  부산  2020-12-31 23:00    -0.7

[17562 rows x 4 columns]

In [ ]:
is_seoul = weatherDF["지점명"] == "서울"
seoul = weatherDF[is_seoul]

temp = []
for date in seoul["일시"]:
    temp.append(date.split(" ")[0])
temp_busan = []
unique_temp = set(temp) #set 자료형으로 형변환
for date in unique_temp:
    if temp.count(date) != 24:
        temp_busan.append(date)

empty_date = [] 
data_date = [] 

for date in seoul["일시"]:
    for temp_date in temp_busan:
        if temp_date in date:
            empty_date.append(date.split(" ")[0])
            data_date.append(date)

empty_date = set(empty_date)
print(empty_date) # 누락된 시간이 있는 날짜
print(data_date) # 그 날짜에서 누락된 시간을 제외한 나머지 시간
print("---")
full_date = []
for date in empty_date:
    for h in range(24):
        full_date.append(date + f" {str(h).zfill(2)}:00")

print(full_date) # 그 날짜에 누락된 시간을 채워 넣음

full_empty_date_seoul = []
for date in full_date:
    if date not in data_date:
        full_empty_date_seoul.append(date)

print(full_empty_date_seoul) # 채워 넣은 시간

In [ ]:
is_busan = weatherDF["지점명"] == "부산"
busan = weatherDF[is_busan]

temp = []
for date in busan["일시"]:
    temp.append(date.split(" ")[0])
temp_busan = []
unique_temp = set(temp) #set 자료형으로 형변환
for date in unique_temp:
    if temp.count(date) != 24:
        temp_busan.append(date)

empty_date = []
data_date = []
for date in busan["일시"]:
    for temp_date in temp_busan:
        if temp_date in date:
            empty_date.append(date.split(" ")[0])
            data_date.append(date)

empty_date = set(empty_date)
print(empty_date)
print(data_date)

full_date = []
for date in empty_date:
    for h in range(24):
        full_date.append(date + f" {str(h).zfill(2)}:00")

print(full_date)

full_empty_date_busan = []
for date in full_date:
    if date not in data_date:
        full_empty_date_busan.append(date)

print(full_empty_date_busan)

In [ ]:
full_empty_date = list(set(full_empty_date_seoul + full_empty_date_busan))

for date in full_empty_date:
    seoul = seoul[seoul["일시"] != date]
    busan = busan[busan["일시"] != date]
    
time = []
for i in range(24):
    time.append(str(i).zfill(2) + ":00")
time

import numpy as np

zeros = np.zeros((24, 2))
df = pd.DataFrame(zeros, index=time, columns=["seoul", "busan"])
df

In [ ]:
seoul

In [ ]:
max_index = []
# 각 시간마다의 기온을 리스트에 담고 그 리스트 중 가장 큰 값의 인덱스를 리스트에 담기

# print(seoul.iloc[0:24, 2].idxmax()) # idxmax > 2열에서 최대 값인 15인덱스

for i in range(0, len(seoul), 24):
    max_index.append(seoul.iloc[i:i+24, 2].idxmax()) # 0 ~ 23 = day / 24 ~ 48 ...

for i in max_index:
    df.loc[seoul.loc[i][1].split(" ")[1]]["seoul"] += 1 # +=1 > 열을 증가시킴

max_index = []

for i in range(0, len(busan), 24):
    max_index.append(busan.iloc[i:i+24, 2].idxmax())

for i in max_index:
    df.loc[busan.loc[i][1].split(" ")[1]]["busan"] += 1

df